[workspace]
members = ["lattice", "lattice-derives", "lattice-sketches"]
resolver = "3"
default-members = ["lattice-sketches"]

# # clean with:
# #   rm -rf target/incremental
# [profile.release]
# incremental = true
