[workspace]
members = ["lattice", "lattice-derives", "sketches"]
resolver = "3"
default-members = ["sketches"]

# # clean with:
# #   rm -rf target/incremental
# [profile.release]
# incremental = true
