[package]
name = "lattice"
version = "0.1.0"
authors = ["Lokua <dev@lokua.net>"]
edition = "2021"

[dependencies]
dirs = "5.0.1"
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"
nannou = "0.19.0"
nannou_egui = "0.19.0"
once_cell = "1.20"
serde = "1.0.215"
serde_json = "1.0.133"

