radius = [
    ["0.0.0", 0.0],
    ["1.0.0", 400.0],
    ["2.0.0", 0.0],
]
# radius = [
#     ["0.0.0", 0.0],
#     ["1.0.0", 500.0],
#     ["2.0.0", 0.0],
# ]
# hue = [
#     ["0.0.0", 0.0],
#     ["1.0.0", 1.0],
#     ["2.0.0", 0.0],
# ]