name: Deploy Rust Docs

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update apt
              run: sudo apt update

            - name: Install alsa dev tools
              run: sudo apt-get install libasound2-dev

            - name: Install libxcb dev tools
              run: sudo apt-get install libxcb-composite0-dev

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Build Documentation
              uses: actions-rs/cargo@v1
              env:
                  RUSTDOCFLAGS: "--cfg docsrs"
                  RUSTFLAGS: "--cfg doc"
              with:
                  command: doc
                  args: --no-deps --document-private-items

            - name: Add index.html redirect
              run: |
                  echo '<meta http-equiv="refresh" content="0; url=lattice/index.html">' > target/doc/index.html

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./target/doc
