name: Deploy Rust Docs

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install system dependencies
              run: |
                  sudo apt-get update && sudo apt-get install -y \
                    libasound2-dev \
                    pkg-config \
                    libudev-dev \
                    libx11-dev \
                    libxcb-composite0-dev \
                    libwayland-dev \
                    libxcb1-dev \
                    libxcb-render0-dev \
                    libxcb-shape0-dev \
                    libxcb-xfixes0-dev

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Build Documentation
              env:
                  RUSTDOCFLAGS: "--cfg docsrs"
                  RUSTFLAGS: "--cfg doc"
              run:
                  cargo doc --no-deps --document-private-items
                  --no-default-features --exclude wayland-scanner --exclude
                  quote

            - name: Add index.html redirect
              run: |
                  echo '<meta http-equiv="refresh" content="0; url=your_project_name/index.html">' > target/doc/index.html

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./target/doc
